export const THINKING_PHRASES = [
  'oh wow, a question. let me pretend to care…',
  'consulting the void…',
  'making something up, just a sec…',
  'definitely not hallucinating right now…',
  'running 47 mental tabs…',
  'staring into the abyss (it blinked)…',
  'calculating your fate, no pressure…',
  'doing the thinking you pay me for…',
  'processing your questionable life choices…',
  'summoning coherent thoughts, rarely works…',
  'asking my imaginary friend for help…',
  'pretending this is a hard problem…',
  'yes, yes, very interesting. anyway…',
  'googling it (not really, I can\'t)…',
  'simulating intelligence… please wait…',
  'having a brief existential crisis…',
  'cross-referencing vibes…',
  'totally not making this up…',
  'the answer is 42. now finding the question…',
  'my other tab is loading…',
  'channelling the spirit of stack overflow…',
  'trying not to confidently be wrong…',
  'applying artificial to the intelligence…',
  'phoning a friend who also doesn\'t know…',
  'checking if this is even my problem to solve…',
  'rebooting common sense… this may take a while…',
  'performing a very convincing impression of thinking…',
  'searching for wisdom in all the wrong places…',
  'warming up the neurons (both of them)…',
  'confidently striding toward the wrong answer…',
  'consulting my gut. it says maybe…',
  'loading… just kidding, still loading…',
  'asking the universe. universe has not replied…',
  'vigorously nodding while understanding nothing…',
  'doing math on my fingers (ran out of fingers)…',
  'the confidence is fake. the effort is real. probably…',
  'entering a fugue state. for your benefit…',
  'mining the depths of mediocrity…',
  'compiling a list of plausible nonsense…',
  'this would be faster if I knew what I was doing…',
  'buffering at the speed of thought…',
  'holding three contradictory opinions simultaneously…',
  'interpolating between guesses…',
  'rewinding the context window with a pencil…',
  'waiting for a sign. any sign…',
  'tracing the error back to its origin: me…',
  'the logic checks out if you squint…',
  'reasoning from first principles I just invented…',
  'generating tokens and praying for coherence…',
  'one sec — dropped all my thoughts, picking them up…',
]

export const SPARKLE = ['✦', '✧', '✶', '✷', '✸', '✹']
